server:
  port: 3000
postgresql:
  host: localhost
  port: 5432
  username: fiber-base
  password: 123456
  dbname: fiber-base
logger:
  log_level: debug
  file_log_name: "./stogares/logs/dev.001.log"
  max_size: 10
  max_backups: 5
  max_age: 30
  compress: true
