server:
  port: 3000

postgresql:
  host: postgres
  port: 5432
  username: fiber-base
  password: ${DB_PASSWORD}
  dbname: fiber-base

redis:
  host: redis
  port: 6379
  password: ""
  db: 0

logger:
  log_level: info
  file_log_name: "./storage/logs/prod.log"
  max_size: 50
  max_backups: 10
  max_age: 30
  compress: true

security:
  jwt_secret: ${JWT_SECRET}
  jwt_expiry: 24h
  bcrypt_cost: 12

rate_limit:
  enabled: true
  max_requests: 100
  window: 60s

cors:
  allowed_origins:
    - "http://localhost:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"
  allow_credentials: true
